### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nnn1590** [Gota7/Citric-Composer#5]
First of all, thank you for making this great application.
Now, what's the license for this application?
Thank you very much.

_This text has been translated from Japanese to English by DeepL Translate and Google Translate._

<details>
<summary>Japanese(Original text)/日本語(原文)</summary>

# ライセンス
まず、この素晴らしいアプリケーションを作ってくれてありがとうございます。
さて、このアプリケーションのライセンスは何ですか？
よろしくお願いします。

_この文章はDeepL 翻訳とGoogle 翻訳で日本語から英語に翻訳されました。_
</details>

**Comment by Gota7** [comment]
All of my code is publicly available for free public use, unless otherwise stated. While I forgot to license this, it would have the GNU General Public License version 3. You are free to use any of this code for noncommercial or commercial purposes, personal or shared use, free to modify or add anything to it, etc. I just only ask that you give credit to me for making the original tool and framework.
